Task 5
ioane-io/Davalebebi pull request #6
Opened 2023-12-14 13:28 UTC by ioane-io

Task 5

2023-12-14 21:13 UTC, AVTUNEY commented on Taks # 5/Vehicle.cs
> +
ეს ორი ცარიელი ლაინი წაშალე, აგრეთვე კლასს გაუკეთე კონსტრუქტორი აუცილებლად. და ფროფერთიები დასეტე

2023-12-14 21:14 UTC, AVTUNEY commented on Taks # 5/Motorcycle.cs
> +    {
კონსტრუქტორი აუცილებლად და გამოიყენოს მშობლის კონსტრუქტორიც `base`

2023-12-14 21:14 UTC, AVTUNEY commented on Taks # 5/Garage.cs
> +                Console.WriteLine();
ეს ლაინი წაშალე

2023-12-14 21:15 UTC, AVTUNEY commented on Taks # 5/Garage.cs
> +            decimal total = 0;
ნუ, `var total = 0.`0 ი უკეტესი იქენბოდა

2023-12-14 21:15 UTC, AVTUNEY commented on Taks # 5/Garage.cs
> +        public List<Vehicle> vehicles = new List<Vehicle>();
private, არასდროს გარედან ამას არ დავუძახებთ

2023-12-14 21:15 UTC, AVTUNEY commented on Taks # 5/Car.cs
> +
empty lines

2023-12-14 21:15 UTC, AVTUNEY commented on Taks # 5/Car.cs
> +        public decimal TrunkCapacity { get; set; }
იგივე აქაც რაც მოტოციკლეტში დაგიწერე, კონსტრუქტორი, მშობლისაც

2023-12-14 21:16 UTC, AVTUNEY requested changes
ცოტაც

2023-12-15 12:28 UTC, ioane-io commented on Taks # 5/Motorcycle.cs
> +    {
ავირიე ამაში და სულ ავურიე მგონი რა :D

2023-12-15 12:28 UTC, AVTUNEY commented on Taks # 5/Motorcycle.cs
> +    {
ჩაიწერე ესენი და ლექციაზე ვიდაუბროთ

2023-12-17 09:19 UTC, merged